import type { Metadata } from 'next';
import { inter } from '@/app/components/fonts';
import './globals.css';

export const metadata: Metadata = {
  title: {
    template: '%s | Next Image Tagger',
    default: 'Next Image Tagger',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>{children}</body>
    </html>
  );
}
