import './globals.css';
import type { Metadata } from 'next';
import { inter } from '@/app/components/fonts';
import { ApolloClientProvider } from '@/app/components/providers/apollo-client-provider';
import { ThemeProvider } from './components/providers/theme-provider';

export const metadata: Metadata = {
  title: {
    template: '%s | Next Image Tagger',
    default: 'Next Image Tagger',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <ApolloClientProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem={true}
          >
            {children}
          </ThemeProvider>
        </ApolloClientProvider>
      </body>
    </html>
  );
}
